export const actionTypes = {
  // Auth
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  UNAUTH_REQUEST: 'UNAUTH_REQUEST',
  AUTH_ERROR: 'AUTH_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  
  // Auth modals
  MODAL_OPENED: 'MODAL_OPENED',
  MODAL_CLOSED: 'MODAL_CLOSED',
  
  // Activity feed
  LOAD_BOOKS: 'LOAD_BOOKS',
  LOAD_DATA_SUCCESS: 'LOAD_DATA_SUCCESS',
  LOAD_DATA_FAILURE: 'LOAD_DATA_FAILURE',
  
  // Session
  SESSION_REQUEST: 'SESSION_REQUEST',
  SESSION_SUCCESS: 'SESSION_SUCCESS',
  SESSION_FAILURE: 'SESSION_FAILURE',
  
  // CSRF
  CSRF_REQUEST: 'CSRF_REQUEST',
  CSRF_SUCCESS: 'CSRF_SUCCESS',
  CSRF_FAILURE: 'CSRF_FAILURE'
}