export const actionTypes = {
  // Auth
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  SIGNOUT_REQUEST: 'SIGNOUT_REQUEST',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNOUT_FAILURE: 'SIGNOUT_FAILURE',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_ERROR: 'AUTH_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  RESET_AUTH_STATE: 'RESET_AUTH_STATE',
  
  // Auth modals
  MODAL_OPENED: 'MODAL_OPENED',
  MODAL_CLOSED: 'MODAL_CLOSED',

  // Sidenav
  SIDENAV_OPENED: 'SIDENAV_OPENED',
  SIDENAV_CLOSED: 'SIDENAV_CLOSED',
  
  // Activity feed
  LOAD_BOOKS: 'LOAD_BOOKS',
  LOAD_DATA_SUCCESS: 'LOAD_DATA_SUCCESS',
  LOAD_DATA_FAILURE: 'LOAD_DATA_FAILURE',
  
  // Session
  SESSION_REQUEST: 'SESSION_REQUEST',
  SESSION_SUCCESS: 'SESSION_SUCCESS',
  SESSION_FAILURE: 'SESSION_FAILURE',
  
  // CSRF
  CSRF_REQUEST: 'CSRF_REQUEST',
  CSRF_SUCCESS: 'CSRF_SUCCESS',
  CSRF_FAILURE: 'CSRF_FAILURE',

  // Providers
  PROVIDERS_REQUEST: 'PROVIDERS_REQUEST',
  PROVIDERS_SUCCESS: 'PROVIDERS_SUCCESS',
  PROVIDERS_FAILURE: 'PROVIDERS_FAILURE',

  // Linked accounts
  LINKED_ACCOUNTS_REQUEST: 'LINKED_ACCOUNTS_REQUEST',
  LINKED_ACCOUNTS_SUCCESS: 'LINKED_ACCOUNTS_SUCCESS',
  LINKED_ACCOUNTS_FAILURE: 'LINKED_ACCOUNTS_FAILURE',
}